version: "3.9"

services:
  exam_service:
    build:
      context: ./vv_exam_management_service
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://exam_db:5432/examdb
      SPRING_DATASOURCE_USERNAME: examuser
      SPRING_DATASOURCE_PASSWORD: exampassword
    volumes:
      - ./vv_exam_management_service:/app
    depends_on:
      - exam_db
    command: ./mvnw spring-boot:run

  school_service:
    build:
      context: ./vv-school-management-service
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://school_db:5432/schooldb
      SPRING_DATASOURCE_USERNAME: schooluser
      SPRING_DATASOURCE_PASSWORD: schoolpassword
    volumes:
      - ./vv-school-management-service:/app
    depends_on:
      - school_db
    command: ./mvnw spring-boot:run

  exam_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: examdb
      POSTGRES_USER: examuser
      POSTGRES_PASSWORD: exampassword
    ports:
      - "5433:5432"
    volumes:
      - exam_db_data:/var/lib/postgresql/data

  school_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: schooldb
      POSTGRES_USER: schooluser
      POSTGRES_PASSWORD: schoolpassword
    ports:
      - "5434:5432"
    volumes:
      - school_db_data:/var/lib/postgresql/data

  keycloak_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: keycloakdb
      POSTGRES_USER: keycloakuser
      POSTGRES_PASSWORD: keycloakpassword
    ports:
      - "5435:5432"
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres                   # Database vendor
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/keycloakdb
      KC_DB_USERNAME: keycloakuser      # Database user
      KC_DB_PASSWORD: keycloakpassword  # Database password
      KC_HOSTNAME: localhost            # Keycloak hostname (change for production)
      KC_HEALTH_ENABLED: "true"         # Enable health checks
      KC_METRICS_ENABLED: "true"        # Enable metrics
      KEYCLOAK_ADMIN: admin             # Keycloak admin username
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8083:8080"
    depends_on:
      - keycloak_db
    command:
      - "start-dev"

volumes:
  exam_db_data:
  school_db_data:
  keycloak_db_data: